"""Shared V2 alpha layer.

The alpha layer deliberately separates:
1) signal/state observation,
2) forward-return estimation,
3) trading-cost hurdle,
4) portfolio/risk execution.

It uses only NumPy/Pandas already present in the application.  A model JSON generated by
research_v2_deep.py can be loaded by Live/Paper/Replay.  Until that model has passed
walk-forward tests, it is explicitly marked `proven: false` and cannot enable production.
"""
from __future__ import annotations
import json
from pathlib import Path
from typing import Any, Dict, Iterable, Optional, Sequence
import numpy as np
import pandas as pd

FEATURES = [
    "r1","r3","r6","r12","retopen","vwdev","rvol","atrpct","rank",
    "breadth","mret","disp","sec_r3","comp","gap","stock_mkt_3","stock_sec_3",
    "range12_pos","bar_pct","or_dist_up","or_dist_dn","body_strength","close_loc","vol_atr"
]


def fit_ridge(X: np.ndarray, y: np.ndarray, alpha: float = 10.0) -> Dict[str, Any]:
    X = np.asarray(X, dtype=float); y = np.asarray(y, dtype=float).reshape(-1)
    mu = np.nanmedian(X, axis=0); X = np.where(np.isfinite(X), X, mu)
    sd = np.nanstd(X, axis=0); sd = np.where((sd < 1e-9) | ~np.isfinite(sd), 1.0, sd)
    Z = (X - mu) / sd
    A = Z.T @ Z + float(alpha) * np.eye(Z.shape[1])
    b = Z.T @ y
    coef = np.linalg.solve(A, b)
    intercept = float(y.mean() - ((mu / sd) @ coef))
    return {"features": list(FEATURES), "mean": mu.tolist(), "scale": sd.tolist(), "coef": coef.tolist(), "intercept": intercept, "alpha": float(alpha)}


def predict(model: Dict[str, Any], row_or_df: pd.DataFrame | Dict[str, Any]) -> np.ndarray:
    feats = list(model.get("features") or FEATURES)
    if isinstance(row_or_df, dict):
        X = np.array([[float(row_or_df.get(f, 0.0) or 0.0) for f in feats]], dtype=float)
    else:
        X = row_or_df[feats].to_numpy(float)
    mu = np.asarray(model.get("mean") or np.zeros(len(feats)), dtype=float)
    sd = np.asarray(model.get("scale") or np.ones(len(feats)), dtype=float)
    coef = np.asarray(model.get("coef") or np.zeros(len(feats)), dtype=float)
    X = np.where(np.isfinite(X), X, mu)
    return ((X - mu) / np.where(sd == 0, 1.0, sd)) @ coef + float(model.get("intercept") or 0.0)


def load_model(path: str | Path) -> Optional[Dict[str, Any]]:
    p = Path(path)
    if not p.exists(): return None
    try: return json.loads(p.read_text())
    except Exception: return None


def save_model(model: Dict[str, Any], path: str | Path) -> None:
    p=Path(path); p.parent.mkdir(parents=True,exist_ok=True); p.write_text(json.dumps(model,indent=2,sort_keys=True))
